### ISSUE TITLE
[ReactNative]Could not find preset "node6" relative to directory dpath

### ISSUE THREAD

**Issue by ancyrweb** [ericelliott/dpath#3]
Happens in ReactNative. 
It works fine when removing .babelrc from the node_modules/dpath.
Should we consider adding .babelrc to .npmignore, since the file is already built in index.js and doesn't require any babeling ?

**Comment by ericelliott** [comment]
We're using babel for the unit tests. It is only required for developing dpath, and should not affect anything else. Where exactly is that error coming from?

**Comment by ancyrweb** [comment]
Surprisingly it didn't happen anymore. 
Anyway, even if node6 is required for testing, it is not required to be shipped with npm, is it ?
